# foundry.toml
[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = ["openzeppelin/=lib/openzeppelin-contracts/","@uniswap/v3-core/=lib/v3-core/","@uniswap/v3-periphery/=lib/v3-periphery/","forge-std/=lib/forge-std/src/"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200